yqboots:
  social:
    wechat:
      app-id: wxe477169329e9e2ae
      app-secret: 6b691fcad677f86ea2583d18013be37d
      partner-id: 1536184451
      partner-key: 1qazxsw23edcvfr45tgbnhy67ujmki89
      token: XXXXXXXXXX
      test-mode: true
      auth:
        access-token-url: https://api.weixin.qq.com/sns/oauth2/access_token?appid={appid}&secret={secret}&code={code}&grant_type={grant_type}
        refresh-token-url: https://api.weixin.qq.com/sns/oauth2/refresh_token?appid={appid}&refresh_token={refresh_token}&grant_type={grant_type}
        check-token-valid-url: https://api.weixin.qq.com/sns/auth?access_token={access_token}&openid={openid}
        get-user-info-url: https://api.weixin.qq.com/sns/userinfo?access_token={access_token}&openid={openid}
      pay:
        cert-path: classpath:META-INF/resources/wxpay/cert/apiclient_cert.p12
        unified-order-url: https://api.mch.weixin.qq.com/pay/unifiedorder
        pay-notify-url: https://www.yqboots.com/wechat/pay/notify
        order-query-url: https://api.mch.weixin.qq.com/pay/orderquery
        order-close-url: https://api.mch.weixin.qq.com/pay/closeorder
        refund-url: https://api.mch.weixin.qq.com/secapi/pay/refund
        refund-notify-url: https://www.yqboots.com/wechat/refund/notify
        refund-query-url: https://api.mch.weixin.qq.com/pay/refundquery
        download-bill-url: https://api.mch.weixin.qq.com/pay/downloadbill
        download-fund-flow-url: https://api.mch.weixin.qq.com/pay/downloadfundflow
        report-url: https://api.mch.weixin.qq.com/payitil/report
        batch-query-comment-url: https://api.mch.weixin.qq.com/billcommentsp/batchquerycomment
spring:
  jpa:
    show-sql: true
